# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

Song.create(name: "3 Peat", song_url: "https://www.youtube.com/watch?v=sINGvrL61VY", album: "Tha Carter III", year: 2008)
Song.create(name: "Mr. Carter", song_url: "https://www.youtube.com/watch?v=-9MIEuMpm44", album: "Tha Carter III", year: 2008)
Song.create(name: "A Milli", song_url: "https://www.youtube.com/watch?v=NdgpcwqBSPg", album: "Tha Carter III", year: 2008)
Song.create(name: "Got Money", song_url: "https://www.youtube.com/watch?v=HD-cnA84zPQ", album: "Tha Carter III", year: 2008)
Song.create(name: "Comfortable", song_url: "https://www.youtube.com/watch?v=qDMm0nKaXVU", album: "Tha Carter III", year: 2008)
Song.create(name: "Dr. Carter", song_url: "https://www.youtube.com/watch?v=es6goNuH0lY", album: "Tha Carter III", year: 2008)
Song.create(name: "Phone Home", song_url: "https://www.youtube.com/watch?v=1Yym6yveYAY", album: "Tha Carter III", year: 2008)
Song.create(name: "Tie My Hands", song_url: "https://www.youtube.com/watch?v=cvr80GN61p4", album: "Tha Carter III", year: 2008)
Song.create(name: "Mrs. Officer", song_url: "https://www.youtube.com/watch?v=buyMOuKDG74", album: "Tha Carter III", year: 2008)
Song.create(name: "Let The Beat Build", song_url: "https://www.youtube.com/watch?v=Wh6stJscR28", album: "Tha Carter III", year: 2008)
Song.create(name: "Shoot Me Down", song_url: "https://www.youtube.com/watch?v=h0mXXLHPoXM", album: "Tha Carter III", year: 2008)
Song.create(name: "Lollipop", song_url: "https://www.youtube.com/watch?v=D-GVWI2_XOA", album: "Tha Carter III", year: 2008)
Song.create(name: "La La", song_url: "https://www.youtube.com/watch?v=LTqidwHIzDw", album: "Tha Carter III", year: 2008)
Song.create(name: "Pussy Monster", song_url: "https://www.youtube.com/watch?v=FHtE1SaKUgs", album: "Tha Carter III", year: 2008)
Song.create(name: "You Ain't Got Nuthin", song_url: "https://www.youtube.com/watch?v=JJNOQX-1V6Y", album: "Tha Carter III", year: 2008)
Song.create(name: "Dontgetit", song_url: "https://www.youtube.com/watch?v=6Y1A5am-mRE", album: "Tha Carter III", year: 2008)
Song.create(name: "Intro", song_url: "https://www.youtube.com/watch?v=M4Z8-wDjaAs&list=PLukJkMJm94mEVIXZChu9WL4_6qFla9uNh", album: "Da Drought 3", year: 2007)
Song.create(name: "Black Republicans", song_url: "https://www.youtube.com/watch?v=grrVwMsarnU&list=PLukJkMJm94mEVIXZChu9WL4_6qFla9uNh&index=2", album: "Da Drought 3", year: 2007)
Song.create(name: "Upgrade", song_url: "https://www.youtube.com/watch?v=QmZV662IMSo&list=PLukJkMJm94mEVIXZChu9WL4_6qFla9uNh&index=3", album: "Da Drought 3", year: 2007)
Song.create(name: "Put Some Keys On That", song_url: "https://www.youtube.com/watch?v=wWQ28wfszp0&list=PLukJkMJm94mEVIXZChu9WL4_6qFla9uNh&index=4", album: "Da Drought 3", year: 2007)
Song.create(name: "Sky's The Limit", album: "Da Drought 3", song_url: "https://www.youtube.com/watch?v=ptRKR6QvJ6w&list=PLukJkMJm94mEVIXZChu9WL4_6qFla9uNh&index=5", year: 2007)
Song.create(name: "Can't Stop, Won't Stop", song_url: "https://www.youtube.com/watch?v=0sQV7VopP-o", album: "Da Drought 3", year: 2007)
Song.create(name: "We Takin Over", song_url: "https://www.youtube.com/watch?v=0VhHKmeqS48&list=PLukJkMJm94mEVIXZChu9WL4_6qFla9uNh&index=6", album: "Da Drought 3", year: 2007)
Song.create(name: "Get High, Rule The World", song_url: "https://www.youtube.com/watch?v=lKIw4oUDtrs&list=PLukJkMJm94mEVIXZChu9WL4_6qFla9uNh&index=7", album: "Da Drought 3", year: 2007)
Song.create(name: "I Can't Feel My Face", song_url: "https://www.youtube.com/watch?v=V2rY9X8NHMU&list=PLukJkMJm94mEVIXZChu9WL4_6qFla9uNh&index=8", album: "Da Drought 3", year: 2007)
Song.create(name: "Dough Is What I Got", song_url: "https://www.youtube.com/watch?v=w1xR7L-Aq9Y", album: "Da Drought 3", year: 2007)
Song.create(name: "Seat Down Low", song_url: "https://www.youtube.com/watch?v=-g3FwG4Sh9U&list=PLukJkMJm94mEVIXZChu9WL4_6qFla9uNh&index=9", album: "Da Drought 3", year: 2007)
Song.create(name: "New Cash Money", song_url: "https://www.youtube.com/watch?v=F07zOFLf5rk", album: "Da Drought 3", year: 2007)
Song.create(name: "Promise", song_url: "https://www.youtube.com/watch?v=_UgaVuQp_sI&list=PLukJkMJm94mEVIXZChu9WL4_6qFla9uNh&index=11", album: "Da Drought 3", year: 2007)
Song.create(name: "Outro", song_url: "https://www.youtube.com/watch?v=Irp6pW4UAIo&list=PLukJkMJm94mEVIXZChu9WL4_6qFla9uNh&index=12", album: "Da Drought 3", year: 2007)
Song.create(name: "Intro", song_url: "https://www.youtube.com/watch?v=a0vIP6gqyow", album: "Da Drought 3", year: 2007)
Song.create(name: "I'm Blooded", song_url: "https://www.youtube.com/watch?v=QLOHHo-0wtY&list=PLukJkMJm94mEVIXZChu9WL4_6qFla9uNh&index=13", album: "Da Drought 3", year: 2007)
Song.create(name: "Live from 504", song_url: "https://www.youtube.com/watch?v=saamzVQ6OyI&list=PLukJkMJm94mEVIXZChu9WL4_6qFla9uNh&index=14", album: "Da Drought 3", year: 2007)
Song.create(name: "King Kong", song_url: "https://www.youtube.com/watch?v=0YPuAX5MsVE&list=PLukJkMJm94mEVIXZChu9WL4_6qFla9uNh&index=15", album: "Da Drought 3", year: 2007)
Song.create(name: "Dipset", song_url: "https://www.youtube.com/watch?v=DJUszYxuVUM&list=PLukJkMJm94mEVIXZChu9WL4_6qFla9uNh&index=16", album: "Da Drought 3", year: 2007)
Song.create(name: "Forever", song_url: "https://www.youtube.com/watch?v=2PnCbUR0D-Y", album: "Da Drought 3", year: 2007)
Song.create(name: "Walk It Out", song_url: "https://www.youtube.com/watch?v=xmWMsNdTEAw", album: "Da Drought 3", year: 2007)
Song.create(name: "Swizzy", song_url: "https://www.youtube.com/watch?v=sJ6-LpbUgYQ&list=PLukJkMJm94mEVIXZChu9WL4_6qFla9uNh&index=17", album: "Da Drought 3", year: 2007)
Song.create(name: "Boom", song_url: "https://www.youtube.com/watch?v=eguQcZCuFn0&list=PLukJkMJm94mEVIXZChu9WL4_6qFla9uNh&index=18", album: "Da Drought 3", year: 2007)
Song.create(name: "N.O. Nigga", song_url: "https://www.youtube.com/watch?v=hQpWYXEHg3A", album: "Da Drought 3", year: 2007)
Song.create(name: "Back On My Grizzy", song_url: "https://www.youtube.com/watch?v=G-KpdeduA6o&list=PLukJkMJm94mEVIXZChu9WL4_6qFla9uNh&index=19", album: "Da Drought 3", year: 2007)
Song.create(name: "Dipset 2", song_url: "https://www.youtube.com/watch?v=F73DGp4R4os&list=PLukJkMJm94mEVIXZChu9WL4_6qFla9uNh&index=20", album: "Da Drought 3", year: 2007)
Song.create(name: "President", song_url: "https://www.youtube.com/watch?v=F-bo-ZpsGM8&list=PLukJkMJm94mEVIXZChu9WL4_6qFla9uNh&index=21", album: "Da Drought 3", year: 2007)
Song.create(name: "Crazy", song_url: "https://www.youtube.com/watch?v=ZvbZcpd-UxY&list=PLukJkMJm94mEVIXZChu9WL4_6qFla9uNh&index=22", album: "Da Drought 3", year: 2007)
Song.create(name: "Outro", song_url: "https://www.youtube.com/watch?v=Eomj1mAtBwk&list=PLukJkMJm94mEVIXZChu9WL4_6qFla9uNh&index=23", album: "Da Drought 3", year: 2007)
Song.create(name: "Swag Surf", song_url: "https://www.youtube.com/watch?v=0dtTLeqkxSQ&list=PL27C08C4B05BBEAAA", album: "No Ceilings", year: 2009)
Song.create(name: "Ice Cream", song_url: "https://www.youtube.com/watch?v=_QUa8eN6qSw&list=PL27C08C4B05BBEAAA&index=2", album: "No Ceilings", year: 2009)
Song.create(name: "Death of Autotune", song_url: "https://www.youtube.com/watch?v=fdYA2kA_lE8&list=PL27C08C4B05BBEAAA&index=3", album: "No Ceilings", year: 2009)
Song.create(name: "Skit 1", song_url: "https://www.youtube.com/watch?v=6sLU9l8DbTA&list=PL27C08C4B05BBEAAA&index=4", album: "No Ceilings", year: 2009)
Song.create(name: "Wasted", song_url: "https://www.youtube.com/watch?v=vJDWRdcx_5o&list=PL27C08C4B05BBEAAA&index=5", album: "No Ceilings", year: 2009)
Song.create(name: "Watch My Shoes", song_url: "https://www.youtube.com/watch?v=ZOxKj7nU2YA", album: "No Ceilings", year: 2009)
Song.create(name: "Break Up", song_url: "https://www.youtube.com/watch?v=gL_EsHZfmKQ&list=PL27C08C4B05BBEAAA&index=7", album: "No Ceilings", year: 2009)
Song.create(name: "Banned from TV", song_url: "https://www.youtube.com/watch?v=4xzVEUrhZEA&list=PL27C08C4B05BBEAAA&index=8", album: "No Ceilings", year: 2009)
Song.create(name: "Throw It In The Bag", song_url: "https://www.youtube.com/watch?v=qAE37yoedfE&list=PL27C08C4B05BBEAAA&index=9", album: "No Ceilings", year: 2009)
Song.create(name: "That's All I Have", song_url: "https://www.youtube.com/watch?v=pn1CrWJz4fI&list=PL27C08C4B05BBEAAA&index=10", album: "No Ceilings", year: 2009)
Song.create(name: "Skit 2", song_url: "https://www.youtube.com/watch?v=JCU6Ld7aWQM&list=PL27C08C4B05BBEAAA&index=11", album: "No Ceilings", year: 2009)
Song.create(name: "Wayne On Me", song_url: "https://www.youtube.com/watch?v=FC3MWmP5OqE", album: "No Ceilings", year: 2009)
Song.create(name: "I'm Good", song_url: "https://www.youtube.com/watch?v=vHJBRjAaf4M&list=PL27C08C4B05BBEAAA&index=12", album: "No Ceilings", year: 2009)
Song.create(name: "Poke Her Face", song_url: "https://www.youtube.com/watch?v=KWeqjuDlgKM&list=PL27C08C4B05BBEAAA&index=13", album: "No Ceilings", year: 2009)
Song.create(name: "Run This Town", song_url: "https://www.youtube.com/watch?v=9YWsOoOhwLM&list=PL27C08C4B05BBEAAA&index=14", album: "No Ceilings", year: 2009)
Song.create(name: "I Got No Ceilings", song_url: "https://www.youtube.com/watch?v=1gaijOOfjYg&list=PL27C08C4B05BBEAAA&index=15", album: "No Ceilings", year: 2009)
Song.create(name: "Skit End", song_url: "https://www.youtube.com/watch?v=fwJqvKdpS-E&list=PL27C08C4B05BBEAAA&index=20", album: "No Ceilings", year: 2009)
Song.create(name: "No Ceilings (Pop That)", song_url: "https://www.youtube.com/watch?v=Lf4Gqg9sMJU&list=PL27C08C4B05BBEAAA&index=18", album: "No Ceilings", year: 2009)
Song.create(name: "Oh Let's Do It", song_url: "https://www.youtube.com/watch?v=cFW3Dyu4h-g&list=PL27C08C4B05BBEAAA&index=19", album: "No Ceilings", year: 2009)
Song.create(name: "I'm Single", song_url: "https://www.youtube.com/watch?v=3PmV-eN4XO8&list=PL27C08C4B05BBEAAA&index=16", album: "No Ceilings", year: 2009)
Song.create(name: "Sweet Dreams", song_url: "https://www.youtube.com/watch?v=-006ORgUlJA&list=PL27C08C4B05BBEAAA&index=17", album: "No Ceilings", year: 2009)
Song.create(name: "Something You Forgot", song_url: "https://www.youtube.com/watch?v=9pzoK-mRK0M", album: "OG Carter III", year: 2008)
